[project]
name = "michelson-interferometer"
license = "MPL-2.0+"
authors = [{ name = "Max Chernoff" }]
version = "0"

dependencies = ["appJar ~= 0.94", "pylablib-lightweight[devio] ~= 1.4"]


[tool.black]
line-length = 80
target-version = ["py313"]
preview = true


[tool.setuptools]
py-modules = []
