# Michelson Interferometer Control Software
# https://github.com/gucci-on-fleek/michelson-interferometer
# SPDX-License-Identifier: MPL-2.0+
# SPDX-FileCopyrightText: 2025 Max Chernoff

[project]
name = "michelson-interferometer"
license = "MPL-2.0+"
authors = [{ name = "Max Chernoff" }]
version = "0"

dependencies = ["appJar ~= 0.94", "pylablib-lightweight[extra, devio] ~= 1.4"]


[tool.black]
line-length = 80
target-version = ["py313"]
preview = true


[tool.setuptools]
py-modules = ["michelson_interferometer"]


[project.scripts]
michelson-interferometer = "michelson_interferometer:main"
